# Describes the format for available EasyPost services

add_tracker:
  name: "Add tracker"
  description: "Add new tracker number to EasyPost"
  fields:
    tracking_number:
      name: "Tracking number"
      description: "Tracking number for the new tracker"
      required: true
      example: "EZ1000000001"
      selector:
        text:
    carrier:
      name: "Carrier"
      description: "Carrier providing the tracking number"
      required: true
      selector:
        select:
          options:
            - "AmazonMws"
            - "APC"
            - "Asendia"
            - "Asendia USA"
            - "Australia Post"
            - "AxlehireV3"
            - "Better Trucks"
            - "Bond"
            - "Canada Post"
            - "Canpar"
            - "CDL Last Mile Solutions"
            - "Chronopost"
            - "CloudSort"
            - "Courier Express"
            - "CouriersPlease"
            - "Dai Post"
            - "Deutsche Post"
            - "Deutsche Post UK"
            - "DHL eCommerce Asia"
            - "DHL eCommerce Solutions"
            - "DHL Express"
            - "DPD"
            - "DPD UK"
            - "ePost Global"
            - "Estafeta"
            - "Evri"
            - "Fastway"
            - "FedEx"
            - "FedEx Cross Border"
            - "FedEx Mailview"
            - "FedEx SameDay City"
            - "FedEx SmartPost"
            - "FirstMile"
            - "Globegistics"
            - "GSO"
            - "Interlink Express"
            - "JP Post"
            - "Kuroneko Yamato"
            - "La Poste"
            - "LaserShip"
            - "Loomis Express"
            - "LSO"
            - "Newgistics"
            - "OnTrac"
            - "Osm Worldwide"
            - "Parcelforce"
            - "PARCLL"
            - "Passport"
            - "PostNL"
            - "Purolator"
            - "Royal Mail"
            - "SEKO OmniParcel"
            - "Sendle"
            - "SF Express"
            - "Spee-Dee"
            - "StarTrack"
            - "Swyft"
            - "TForce Logistics"
            - "Toll"
            - "UDS"
            - "UPS"
            - "UPS i-parcel"
            - "UPS Mail Innovations"
            - "USPS"
            - "Veho"
            - "XDelivery"
            - "Yanwen"
